# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\ronlineTracker\"3\n\x0e\x43onnectRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\x04\"6\n\x11\x44isconnectRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\x04\"\x06\n\x04Void2\x9b\x01\n\rOnlineTracker\x12\x41\n\tonConnect\x12\x1d.onlineTracker.ConnectRequest\x1a\x13.onlineTracker.Void\"\x00\x12G\n\x0conDisconnect\x12 .onlineTracker.DisconnectRequest\x1a\x13.onlineTracker.Void\"\x00\x42\x1b\n\x17\x63om.proto.onlineTrackerP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.proto.onlineTrackerP\001'
  _globals['_CONNECTREQUEST']._serialized_start=29
  _globals['_CONNECTREQUEST']._serialized_end=80
  _globals['_DISCONNECTREQUEST']._serialized_start=82
  _globals['_DISCONNECTREQUEST']._serialized_end=136
  _globals['_VOID']._serialized_start=138
  _globals['_VOID']._serialized_end=144
  _globals['_ONLINETRACKER']._serialized_start=147
  _globals['_ONLINETRACKER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
