# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.pyproto.main_pb2 as main__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OnlineTrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.onConnect = channel.unary_unary(
                '/onlineTracker.OnlineTracker/onConnect',
                request_serializer=main__pb2.ConnectRequest.SerializeToString,
                response_deserializer=main__pb2.Void.FromString,
                _registered_method=True)
        self.onDisconnect = channel.unary_unary(
                '/onlineTracker.OnlineTracker/onDisconnect',
                request_serializer=main__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=main__pb2.Void.FromString,
                _registered_method=True)


class OnlineTrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def onConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def onDisconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OnlineTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'onConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.onConnect,
                    request_deserializer=main__pb2.ConnectRequest.FromString,
                    response_serializer=main__pb2.Void.SerializeToString,
            ),
            'onDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.onDisconnect,
                    request_deserializer=main__pb2.DisconnectRequest.FromString,
                    response_serializer=main__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onlineTracker.OnlineTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onlineTracker.OnlineTracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OnlineTracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def onConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onlineTracker.OnlineTracker/onConnect',
            main__pb2.ConnectRequest.SerializeToString,
            main__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def onDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onlineTracker.OnlineTracker/onDisconnect',
            main__pb2.DisconnectRequest.SerializeToString,
            main__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
